name: Build Sniper Arena HUD mod

on:
  push:
    paths:
      - 'hud_mod/**'
      - '.github/workflows/hud-mod.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: hud_mod
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.1.1'
      - name: Build
        working-directory: hud_mod
        run: gradle build --no-daemon --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: sniper_arena_hud
          path: hud_mod/build/libs/*.jar
